# manipulator:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
manipulator:
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.00001
# manipulator:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   solve_type: Manip2
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.001
# manipulator:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedTRACKinematicsPlugin
#   solve_type: Manip2
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.001
#   max_cache_size: 10000
# manipulator:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedUR5KinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.0005
#   max_cache_size: 10000
